### ISSUE TITLE
Clipper submodule missing

### ISSUE THREAD

**Issue by 3dodev** [jbuckmccready/CavalierContoursDev#6]
"error: could not find git for clone of clipper_static-populate"
I'm not able to build on Win10, MSVC2019, QT5.15.2, Cmake 3.19.0,  following the instructions because https://github.com/jbuckmccready/clipper-lib is not downloading during the build process using include(clipper.cmake) finding the GIT fails. Github desktop is installed. Attempting to manually include the clipper repository requested by the cmake file is creating other issues for me. Can you make clipper a submodule as that seems to work for CavalierContours, or advise on the details of including Clipper?

**Comment by jbuckmccready** [comment]
From the error message I think it's due to git not being in the `PATH` environment variable at the time that CMake is running. You can check if git is in your user/system wide `PATH` environment variable by opening a `cmd` prompt and inputting `where git`. If it can't be found then it needs to be added.

**Comment by 3dodev** [comment]
Success! I had Github desktop, but not Git installed. Maybe add to the instructions "install GIT" for the uninitiated.

**Comment by jbuckmccready** [comment]
I'm adding a note about ensuring git is in your `PATH` environment variable as it is required to clone and download clipper and google test.
